#output.logstash:
 # hosts: ["logstash:5044"]

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: http://kibana:5601
  # If set to true, replace dots in labels with `_`.
  #labels.dedot: false

  # If set to true, collects metrics per core.
  #cpu.cores: true

  # To connect to Docker over TLS you must specify a client and CA certificate.
  #ssl:
    #certificate_authority: "/etc/pki/root/ca.pem"
    #certificate:           "/etc/pki/client/cert.pem"
    #key:                   "/etc/pki/client/cert.key"
