version: '3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    deploy:
      replicas: 1
    container_name: kibana
    image: kibana:6.5.4
    volumes:
      - kibana:/usr/share/kibana/data
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet 
  logstash:
    deploy:
      replicas: 1
    build:
      context: ./logstash
    container_name: logstash
    image: nmlynch/logstash:6.5.4
    environment:
      - "LOG_LEVEL=debug"
    volumes:
      - ./logs_to_import:/usr/share/logstash/data_import
    ports: 
      - 5044:5044
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  kibana:
    driver: local
  

networks:
  esnet:
