version: '3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    image: lynchy901/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    container_name: kibana
    image: kibana:6.5.4
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet 
  logstash:
    build:
      context: ./logstash
    container_name: logstash
    image: lynchy901/logstash:6.5.4
    ports: 
      - 5044:5044
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
