version: '3'
services:
  emitter:
    build:
      context: ./
    image: lynchy901/emitter:latest
    deploy:
      replicas: 1
    volumes:
      - log_data:/home/logs/
    networks:
      - lognet
  filebeat:
    command: /bin/bash -c "./filebeat -e -d "publish""
    deploy:
      replicas: 1
    build:
      context: ./filebeats
    image: lynchy901/filebeats:6.5.4
    volumes:
      - log_data:/var/logs/
    networks:
      - lognet 
  metricbeat:
    deploy:
      replicas: 1
    build:
      context: ./metricbeat
    image: lynchy901/metricbeat:6.5.4
    networks:
      - lognet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  lognet:
    external:
      name: elasticstack_esnet

volumes:
  log_data:
    driver: local
