version: '3'
services:
  emitter:
    container_name: time_emitter
    image: emitter:latest
    volumes:
      - log_data:/home/logs/
    networks:
      - lognet
  filebeat:
    command: /bin/bash -c "./filebeat -e -d "publish""
    container_name: filebeat
    image: filebeats:latest
    volumes:
      - log_data:/var/logs/
    networks:
      - lognet 
  metricbeat:
    container_name: metricbeat
    image: metricbeat:latest
    networks:
      - lognet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  lognet:
    external:
      name: elasticstack_esnet

volumes:
  log_data:
    driver: local
